// Copyright (c) 2024-2026 Apptly Software Ltd <oss@apptly.co>
// SPDX-License-Identifier: MIT
//
// ACME Account Resource (RFC 8555)

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: acme/v1/account.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AccountStatus represents the status of an ACME account.
// RFC 8555 §7.1.6
type AccountStatus int32

const (
	// Unspecified account status.
	AccountStatus_ACCOUNT_STATUS_UNSPECIFIED AccountStatus = 0
	// Account is active and can be used.
	AccountStatus_ACCOUNT_STATUS_VALID AccountStatus = 1
	// Account was deactivated by the client.
	AccountStatus_ACCOUNT_STATUS_DEACTIVATED AccountStatus = 2
	// Account was revoked by the server.
	AccountStatus_ACCOUNT_STATUS_REVOKED AccountStatus = 3
)

// Enum value maps for AccountStatus.
var (
	AccountStatus_name = map[int32]string{
		0: "ACCOUNT_STATUS_UNSPECIFIED",
		1: "ACCOUNT_STATUS_VALID",
		2: "ACCOUNT_STATUS_DEACTIVATED",
		3: "ACCOUNT_STATUS_REVOKED",
	}
	AccountStatus_value = map[string]int32{
		"ACCOUNT_STATUS_UNSPECIFIED": 0,
		"ACCOUNT_STATUS_VALID":       1,
		"ACCOUNT_STATUS_DEACTIVATED": 2,
		"ACCOUNT_STATUS_REVOKED":     3,
	}
)

func (x AccountStatus) Enum() *AccountStatus {
	p := new(AccountStatus)
	*p = x
	return p
}

func (x AccountStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_acme_v1_account_proto_enumTypes[0].Descriptor()
}

func (AccountStatus) Type() protoreflect.EnumType {
	return &file_acme_v1_account_proto_enumTypes[0]
}

func (x AccountStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountStatus.Descriptor instead.
func (AccountStatus) EnumDescriptor() ([]byte, []int) {
	return file_acme_v1_account_proto_rawDescGZIP(), []int{0}
}

// Account represents an ACME account.
// RFC 8555 §7.1.2
type Account struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current status of the account.
	Status AccountStatus `protobuf:"varint,1,opt,name=status,proto3,enum=acme.v1.AccountStatus" json:"status,omitempty"`
	// Contact URLs (e.g., mailto:) for the account holder.
	Contact []string `protobuf:"bytes,2,rep,name=contact,proto3" json:"contact,omitempty"`
	// Indicates the client's agreement with the terms of service.
	TermsOfServiceAgreed bool `protobuf:"varint,3,opt,name=terms_of_service_agreed,json=termsOfServiceAgreed,proto3" json:"terms_of_service_agreed,omitempty"`
	// URL from which the list of orders for this account can be fetched.
	Orders        string `protobuf:"bytes,4,opt,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_acme_v1_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_acme_v1_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_acme_v1_account_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetStatus() AccountStatus {
	if x != nil {
		return x.Status
	}
	return AccountStatus_ACCOUNT_STATUS_UNSPECIFIED
}

func (x *Account) GetContact() []string {
	if x != nil {
		return x.Contact
	}
	return nil
}

func (x *Account) GetTermsOfServiceAgreed() bool {
	if x != nil {
		return x.TermsOfServiceAgreed
	}
	return false
}

func (x *Account) GetOrders() string {
	if x != nil {
		return x.Orders
	}
	return ""
}

var File_acme_v1_account_proto protoreflect.FileDescriptor

const file_acme_v1_account_proto_rawDesc = "" +
	"\n" +
	"\x15acme/v1/account.proto\x12\aacme.v1\"\xa2\x01\n" +
	"\aAccount\x12.\n" +
	"\x06status\x18\x01 \x01(\x0e2\x16.acme.v1.AccountStatusR\x06status\x12\x18\n" +
	"\acontact\x18\x02 \x03(\tR\acontact\x125\n" +
	"\x17terms_of_service_agreed\x18\x03 \x01(\bR\x14termsOfServiceAgreed\x12\x16\n" +
	"\x06orders\x18\x04 \x01(\tR\x06orders*\x85\x01\n" +
	"\rAccountStatus\x12\x1e\n" +
	"\x1aACCOUNT_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ACCOUNT_STATUS_VALID\x10\x01\x12\x1e\n" +
	"\x1aACCOUNT_STATUS_DEACTIVATED\x10\x02\x12\x1a\n" +
	"\x16ACCOUNT_STATUS_REVOKED\x10\x03B%Z#darvaza.org/wilee/pkg/specs/acme/v1b\x06proto3"

var (
	file_acme_v1_account_proto_rawDescOnce sync.Once
	file_acme_v1_account_proto_rawDescData []byte
)

func file_acme_v1_account_proto_rawDescGZIP() []byte {
	file_acme_v1_account_proto_rawDescOnce.Do(func() {
		file_acme_v1_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_acme_v1_account_proto_rawDesc), len(file_acme_v1_account_proto_rawDesc)))
	})
	return file_acme_v1_account_proto_rawDescData
}

var file_acme_v1_account_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_acme_v1_account_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_acme_v1_account_proto_goTypes = []any{
	(AccountStatus)(0), // 0: acme.v1.AccountStatus
	(*Account)(nil),    // 1: acme.v1.Account
}
var file_acme_v1_account_proto_depIdxs = []int32{
	0, // 0: acme.v1.Account.status:type_name -> acme.v1.AccountStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_acme_v1_account_proto_init() }
func file_acme_v1_account_proto_init() {
	if File_acme_v1_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_acme_v1_account_proto_rawDesc), len(file_acme_v1_account_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_acme_v1_account_proto_goTypes,
		DependencyIndexes: file_acme_v1_account_proto_depIdxs,
		EnumInfos:         file_acme_v1_account_proto_enumTypes,
		MessageInfos:      file_acme_v1_account_proto_msgTypes,
	}.Build()
	File_acme_v1_account_proto = out.File
	file_acme_v1_account_proto_goTypes = nil
	file_acme_v1_account_proto_depIdxs = nil
}
