// Copyright (c) 2024-2026 Apptly Software Ltd <oss@apptly.co>
// SPDX-License-Identifier: MIT
//
// ACME Core Types (RFC 8555)

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: acme/v1/acme.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IdentifierType specifies the type of identifier.
// RFC 8555 §9.7.7
type IdentifierType int32

const (
	// Unspecified identifier type.
	IdentifierType_IDENTIFIER_TYPE_UNSPECIFIED IdentifierType = 0
	// DNS domain name.
	IdentifierType_IDENTIFIER_TYPE_DNS IdentifierType = 1
	// IP address (RFC 8738).
	IdentifierType_IDENTIFIER_TYPE_IP IdentifierType = 2
)

// Enum value maps for IdentifierType.
var (
	IdentifierType_name = map[int32]string{
		0: "IDENTIFIER_TYPE_UNSPECIFIED",
		1: "IDENTIFIER_TYPE_DNS",
		2: "IDENTIFIER_TYPE_IP",
	}
	IdentifierType_value = map[string]int32{
		"IDENTIFIER_TYPE_UNSPECIFIED": 0,
		"IDENTIFIER_TYPE_DNS":         1,
		"IDENTIFIER_TYPE_IP":          2,
	}
)

func (x IdentifierType) Enum() *IdentifierType {
	p := new(IdentifierType)
	*p = x
	return p
}

func (x IdentifierType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IdentifierType) Descriptor() protoreflect.EnumDescriptor {
	return file_acme_v1_acme_proto_enumTypes[0].Descriptor()
}

func (IdentifierType) Type() protoreflect.EnumType {
	return &file_acme_v1_acme_proto_enumTypes[0]
}

func (x IdentifierType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IdentifierType.Descriptor instead.
func (IdentifierType) EnumDescriptor() ([]byte, []int) {
	return file_acme_v1_acme_proto_rawDescGZIP(), []int{0}
}

// Identifier represents an identifier for certificate issuance.
// RFC 8555 §9.7.7
type Identifier struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of identifier (e.g., dns, ip).
	Type IdentifierType `protobuf:"varint,1,opt,name=type,proto3,enum=acme.v1.IdentifierType" json:"type,omitempty"`
	// The identifier itself (e.g., domain name or IP address).
	Value         string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identifier) Reset() {
	*x = Identifier{}
	mi := &file_acme_v1_acme_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identifier) ProtoMessage() {}

func (x *Identifier) ProtoReflect() protoreflect.Message {
	mi := &file_acme_v1_acme_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identifier.ProtoReflect.Descriptor instead.
func (*Identifier) Descriptor() ([]byte, []int) {
	return file_acme_v1_acme_proto_rawDescGZIP(), []int{0}
}

func (x *Identifier) GetType() IdentifierType {
	if x != nil {
		return x.Type
	}
	return IdentifierType_IDENTIFIER_TYPE_UNSPECIFIED
}

func (x *Identifier) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// DirectoryMeta contains metadata about an ACME server.
// RFC 8555 §7.1.1
type DirectoryMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// URL identifying the current terms of service.
	TermsOfService string `protobuf:"bytes,1,opt,name=terms_of_service,json=termsOfService,proto3" json:"terms_of_service,omitempty"`
	// URL locating a website providing more information about the CA.
	Website string `protobuf:"bytes,2,opt,name=website,proto3" json:"website,omitempty"`
	// Hostnames which the ACME server recognises as referring to itself.
	CaaIdentities []string `protobuf:"bytes,3,rep,name=caa_identities,json=caaIdentities,proto3" json:"caa_identities,omitempty"`
	// Indicates whether an external account is required for newAccount.
	ExternalAccountRequired bool `protobuf:"varint,4,opt,name=external_account_required,json=externalAccountRequired,proto3" json:"external_account_required,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *DirectoryMeta) Reset() {
	*x = DirectoryMeta{}
	mi := &file_acme_v1_acme_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectoryMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectoryMeta) ProtoMessage() {}

func (x *DirectoryMeta) ProtoReflect() protoreflect.Message {
	mi := &file_acme_v1_acme_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectoryMeta.ProtoReflect.Descriptor instead.
func (*DirectoryMeta) Descriptor() ([]byte, []int) {
	return file_acme_v1_acme_proto_rawDescGZIP(), []int{1}
}

func (x *DirectoryMeta) GetTermsOfService() string {
	if x != nil {
		return x.TermsOfService
	}
	return ""
}

func (x *DirectoryMeta) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *DirectoryMeta) GetCaaIdentities() []string {
	if x != nil {
		return x.CaaIdentities
	}
	return nil
}

func (x *DirectoryMeta) GetExternalAccountRequired() bool {
	if x != nil {
		return x.ExternalAccountRequired
	}
	return false
}

// Directory provides URLs for ACME resources.
// RFC 8555 §7.1.1
type Directory struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// URL for requesting a fresh nonce.
	NewNonce string `protobuf:"bytes,1,opt,name=new_nonce,json=newNonce,proto3" json:"new_nonce,omitempty"`
	// URL for creating a new account.
	NewAccount string `protobuf:"bytes,2,opt,name=new_account,json=newAccount,proto3" json:"new_account,omitempty"`
	// URL for submitting a new order.
	NewOrder string `protobuf:"bytes,3,opt,name=new_order,json=newOrder,proto3" json:"new_order,omitempty"`
	// URL for pre-authorisation requests (optional).
	NewAuthz string `protobuf:"bytes,4,opt,name=new_authz,json=newAuthz,proto3" json:"new_authz,omitempty"`
	// URL for certificate revocation requests.
	RevokeCert string `protobuf:"bytes,5,opt,name=revoke_cert,json=revokeCert,proto3" json:"revoke_cert,omitempty"`
	// URL for account key rollover.
	KeyChange string `protobuf:"bytes,6,opt,name=key_change,json=keyChange,proto3" json:"key_change,omitempty"`
	// Additional server metadata.
	Meta          *DirectoryMeta `protobuf:"bytes,7,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Directory) Reset() {
	*x = Directory{}
	mi := &file_acme_v1_acme_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Directory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Directory) ProtoMessage() {}

func (x *Directory) ProtoReflect() protoreflect.Message {
	mi := &file_acme_v1_acme_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Directory.ProtoReflect.Descriptor instead.
func (*Directory) Descriptor() ([]byte, []int) {
	return file_acme_v1_acme_proto_rawDescGZIP(), []int{2}
}

func (x *Directory) GetNewNonce() string {
	if x != nil {
		return x.NewNonce
	}
	return ""
}

func (x *Directory) GetNewAccount() string {
	if x != nil {
		return x.NewAccount
	}
	return ""
}

func (x *Directory) GetNewOrder() string {
	if x != nil {
		return x.NewOrder
	}
	return ""
}

func (x *Directory) GetNewAuthz() string {
	if x != nil {
		return x.NewAuthz
	}
	return ""
}

func (x *Directory) GetRevokeCert() string {
	if x != nil {
		return x.RevokeCert
	}
	return ""
}

func (x *Directory) GetKeyChange() string {
	if x != nil {
		return x.KeyChange
	}
	return ""
}

func (x *Directory) GetMeta() *DirectoryMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

var File_acme_v1_acme_proto protoreflect.FileDescriptor

const file_acme_v1_acme_proto_rawDesc = "" +
	"\n" +
	"\x12acme/v1/acme.proto\x12\aacme.v1\"O\n" +
	"\n" +
	"Identifier\x12+\n" +
	"\x04type\x18\x01 \x01(\x0e2\x17.acme.v1.IdentifierTypeR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xb6\x01\n" +
	"\rDirectoryMeta\x12(\n" +
	"\x10terms_of_service\x18\x01 \x01(\tR\x0etermsOfService\x12\x18\n" +
	"\awebsite\x18\x02 \x01(\tR\awebsite\x12%\n" +
	"\x0ecaa_identities\x18\x03 \x03(\tR\rcaaIdentities\x12:\n" +
	"\x19external_account_required\x18\x04 \x01(\bR\x17externalAccountRequired\"\xef\x01\n" +
	"\tDirectory\x12\x1b\n" +
	"\tnew_nonce\x18\x01 \x01(\tR\bnewNonce\x12\x1f\n" +
	"\vnew_account\x18\x02 \x01(\tR\n" +
	"newAccount\x12\x1b\n" +
	"\tnew_order\x18\x03 \x01(\tR\bnewOrder\x12\x1b\n" +
	"\tnew_authz\x18\x04 \x01(\tR\bnewAuthz\x12\x1f\n" +
	"\vrevoke_cert\x18\x05 \x01(\tR\n" +
	"revokeCert\x12\x1d\n" +
	"\n" +
	"key_change\x18\x06 \x01(\tR\tkeyChange\x12*\n" +
	"\x04meta\x18\a \x01(\v2\x16.acme.v1.DirectoryMetaR\x04meta*b\n" +
	"\x0eIdentifierType\x12\x1f\n" +
	"\x1bIDENTIFIER_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13IDENTIFIER_TYPE_DNS\x10\x01\x12\x16\n" +
	"\x12IDENTIFIER_TYPE_IP\x10\x02B%Z#darvaza.org/wilee/pkg/specs/acme/v1b\x06proto3"

var (
	file_acme_v1_acme_proto_rawDescOnce sync.Once
	file_acme_v1_acme_proto_rawDescData []byte
)

func file_acme_v1_acme_proto_rawDescGZIP() []byte {
	file_acme_v1_acme_proto_rawDescOnce.Do(func() {
		file_acme_v1_acme_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_acme_v1_acme_proto_rawDesc), len(file_acme_v1_acme_proto_rawDesc)))
	})
	return file_acme_v1_acme_proto_rawDescData
}

var file_acme_v1_acme_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_acme_v1_acme_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_acme_v1_acme_proto_goTypes = []any{
	(IdentifierType)(0),   // 0: acme.v1.IdentifierType
	(*Identifier)(nil),    // 1: acme.v1.Identifier
	(*DirectoryMeta)(nil), // 2: acme.v1.DirectoryMeta
	(*Directory)(nil),     // 3: acme.v1.Directory
}
var file_acme_v1_acme_proto_depIdxs = []int32{
	0, // 0: acme.v1.Identifier.type:type_name -> acme.v1.IdentifierType
	2, // 1: acme.v1.Directory.meta:type_name -> acme.v1.DirectoryMeta
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_acme_v1_acme_proto_init() }
func file_acme_v1_acme_proto_init() {
	if File_acme_v1_acme_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_acme_v1_acme_proto_rawDesc), len(file_acme_v1_acme_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_acme_v1_acme_proto_goTypes,
		DependencyIndexes: file_acme_v1_acme_proto_depIdxs,
		EnumInfos:         file_acme_v1_acme_proto_enumTypes,
		MessageInfos:      file_acme_v1_acme_proto_msgTypes,
	}.Build()
	File_acme_v1_acme_proto = out.File
	file_acme_v1_acme_proto_goTypes = nil
	file_acme_v1_acme_proto_depIdxs = nil
}
