// Copyright (c) 2024-2026 Apptly Software Ltd <oss@apptly.co>
// SPDX-License-Identifier: MIT
//
// ACME Authorization Resource (RFC 8555)

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: acme/v1/authorization.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AuthorizationStatus represents the status of an ACME authorisation.
// RFC 8555 §7.1.6
type AuthorizationStatus int32

const (
	// Unspecified authorisation status.
	AuthorizationStatus_AUTHORIZATION_STATUS_UNSPECIFIED AuthorizationStatus = 0
	// Authorisation is awaiting challenge completion.
	AuthorizationStatus_AUTHORIZATION_STATUS_PENDING AuthorizationStatus = 1
	// A challenge was successfully completed.
	AuthorizationStatus_AUTHORIZATION_STATUS_VALID AuthorizationStatus = 2
	// The client failed to complete a challenge.
	AuthorizationStatus_AUTHORIZATION_STATUS_INVALID AuthorizationStatus = 3
	// The client deactivated the authorisation.
	AuthorizationStatus_AUTHORIZATION_STATUS_DEACTIVATED AuthorizationStatus = 4
	// The authorisation has expired.
	AuthorizationStatus_AUTHORIZATION_STATUS_EXPIRED AuthorizationStatus = 5
	// The server revoked the authorisation.
	AuthorizationStatus_AUTHORIZATION_STATUS_REVOKED AuthorizationStatus = 6
)

// Enum value maps for AuthorizationStatus.
var (
	AuthorizationStatus_name = map[int32]string{
		0: "AUTHORIZATION_STATUS_UNSPECIFIED",
		1: "AUTHORIZATION_STATUS_PENDING",
		2: "AUTHORIZATION_STATUS_VALID",
		3: "AUTHORIZATION_STATUS_INVALID",
		4: "AUTHORIZATION_STATUS_DEACTIVATED",
		5: "AUTHORIZATION_STATUS_EXPIRED",
		6: "AUTHORIZATION_STATUS_REVOKED",
	}
	AuthorizationStatus_value = map[string]int32{
		"AUTHORIZATION_STATUS_UNSPECIFIED": 0,
		"AUTHORIZATION_STATUS_PENDING":     1,
		"AUTHORIZATION_STATUS_VALID":       2,
		"AUTHORIZATION_STATUS_INVALID":     3,
		"AUTHORIZATION_STATUS_DEACTIVATED": 4,
		"AUTHORIZATION_STATUS_EXPIRED":     5,
		"AUTHORIZATION_STATUS_REVOKED":     6,
	}
)

func (x AuthorizationStatus) Enum() *AuthorizationStatus {
	p := new(AuthorizationStatus)
	*p = x
	return p
}

func (x AuthorizationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthorizationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_acme_v1_authorization_proto_enumTypes[0].Descriptor()
}

func (AuthorizationStatus) Type() protoreflect.EnumType {
	return &file_acme_v1_authorization_proto_enumTypes[0]
}

func (x AuthorizationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthorizationStatus.Descriptor instead.
func (AuthorizationStatus) EnumDescriptor() ([]byte, []int) {
	return file_acme_v1_authorization_proto_rawDescGZIP(), []int{0}
}

// Authorization represents an authorisation for an identifier.
// RFC 8555 §7.1.4
type Authorization struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The identifier that the account is authorised to represent.
	Identifier *Identifier `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	// Current status of the authorisation.
	Status AuthorizationStatus `protobuf:"varint,2,opt,name=status,proto3,enum=acme.v1.AuthorizationStatus" json:"status,omitempty"`
	// Timestamp after which the server will consider this authorisation invalid.
	Expires string `protobuf:"bytes,3,opt,name=expires,proto3" json:"expires,omitempty"`
	// Array of challenge objects that the client can fulfil to prove control.
	Challenges []*Challenge `protobuf:"bytes,4,rep,name=challenges,proto3" json:"challenges,omitempty"`
	// Indicates this authorisation is for wildcard DNS identifier.
	Wildcard      bool `protobuf:"varint,5,opt,name=wildcard,proto3" json:"wildcard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Authorization) Reset() {
	*x = Authorization{}
	mi := &file_acme_v1_authorization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Authorization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authorization) ProtoMessage() {}

func (x *Authorization) ProtoReflect() protoreflect.Message {
	mi := &file_acme_v1_authorization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authorization.ProtoReflect.Descriptor instead.
func (*Authorization) Descriptor() ([]byte, []int) {
	return file_acme_v1_authorization_proto_rawDescGZIP(), []int{0}
}

func (x *Authorization) GetIdentifier() *Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *Authorization) GetStatus() AuthorizationStatus {
	if x != nil {
		return x.Status
	}
	return AuthorizationStatus_AUTHORIZATION_STATUS_UNSPECIFIED
}

func (x *Authorization) GetExpires() string {
	if x != nil {
		return x.Expires
	}
	return ""
}

func (x *Authorization) GetChallenges() []*Challenge {
	if x != nil {
		return x.Challenges
	}
	return nil
}

func (x *Authorization) GetWildcard() bool {
	if x != nil {
		return x.Wildcard
	}
	return false
}

var File_acme_v1_authorization_proto protoreflect.FileDescriptor

const file_acme_v1_authorization_proto_rawDesc = "" +
	"\n" +
	"\x1bacme/v1/authorization.proto\x12\aacme.v1\x1a\x12acme/v1/acme.proto\x1a\x17acme/v1/challenge.proto\"\xe4\x01\n" +
	"\rAuthorization\x123\n" +
	"\n" +
	"identifier\x18\x01 \x01(\v2\x13.acme.v1.IdentifierR\n" +
	"identifier\x124\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1c.acme.v1.AuthorizationStatusR\x06status\x12\x18\n" +
	"\aexpires\x18\x03 \x01(\tR\aexpires\x122\n" +
	"\n" +
	"challenges\x18\x04 \x03(\v2\x12.acme.v1.ChallengeR\n" +
	"challenges\x12\x1a\n" +
	"\bwildcard\x18\x05 \x01(\bR\bwildcard*\x89\x02\n" +
	"\x13AuthorizationStatus\x12$\n" +
	" AUTHORIZATION_STATUS_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cAUTHORIZATION_STATUS_PENDING\x10\x01\x12\x1e\n" +
	"\x1aAUTHORIZATION_STATUS_VALID\x10\x02\x12 \n" +
	"\x1cAUTHORIZATION_STATUS_INVALID\x10\x03\x12$\n" +
	" AUTHORIZATION_STATUS_DEACTIVATED\x10\x04\x12 \n" +
	"\x1cAUTHORIZATION_STATUS_EXPIRED\x10\x05\x12 \n" +
	"\x1cAUTHORIZATION_STATUS_REVOKED\x10\x06B%Z#darvaza.org/wilee/pkg/specs/acme/v1b\x06proto3"

var (
	file_acme_v1_authorization_proto_rawDescOnce sync.Once
	file_acme_v1_authorization_proto_rawDescData []byte
)

func file_acme_v1_authorization_proto_rawDescGZIP() []byte {
	file_acme_v1_authorization_proto_rawDescOnce.Do(func() {
		file_acme_v1_authorization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_acme_v1_authorization_proto_rawDesc), len(file_acme_v1_authorization_proto_rawDesc)))
	})
	return file_acme_v1_authorization_proto_rawDescData
}

var file_acme_v1_authorization_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_acme_v1_authorization_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_acme_v1_authorization_proto_goTypes = []any{
	(AuthorizationStatus)(0), // 0: acme.v1.AuthorizationStatus
	(*Authorization)(nil),    // 1: acme.v1.Authorization
	(*Identifier)(nil),       // 2: acme.v1.Identifier
	(*Challenge)(nil),        // 3: acme.v1.Challenge
}
var file_acme_v1_authorization_proto_depIdxs = []int32{
	2, // 0: acme.v1.Authorization.identifier:type_name -> acme.v1.Identifier
	0, // 1: acme.v1.Authorization.status:type_name -> acme.v1.AuthorizationStatus
	3, // 2: acme.v1.Authorization.challenges:type_name -> acme.v1.Challenge
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_acme_v1_authorization_proto_init() }
func file_acme_v1_authorization_proto_init() {
	if File_acme_v1_authorization_proto != nil {
		return
	}
	file_acme_v1_acme_proto_init()
	file_acme_v1_challenge_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_acme_v1_authorization_proto_rawDesc), len(file_acme_v1_authorization_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_acme_v1_authorization_proto_goTypes,
		DependencyIndexes: file_acme_v1_authorization_proto_depIdxs,
		EnumInfos:         file_acme_v1_authorization_proto_enumTypes,
		MessageInfos:      file_acme_v1_authorization_proto_msgTypes,
	}.Build()
	File_acme_v1_authorization_proto = out.File
	file_acme_v1_authorization_proto_goTypes = nil
	file_acme_v1_authorization_proto_depIdxs = nil
}
