// Copyright (c) 2024-2026 Apptly Software Ltd <oss@apptly.co>
// SPDX-License-Identifier: MIT
//
// ACME Challenge Resource (RFC 8555)

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: acme/v1/challenge.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ChallengeStatus represents the status of an ACME challenge.
// RFC 8555 §7.1.6
type ChallengeStatus int32

const (
	// Unspecified challenge status.
	ChallengeStatus_CHALLENGE_STATUS_UNSPECIFIED ChallengeStatus = 0
	// Challenge is available for the client to respond to.
	ChallengeStatus_CHALLENGE_STATUS_PENDING ChallengeStatus = 1
	// Server is validating the client's response.
	ChallengeStatus_CHALLENGE_STATUS_PROCESSING ChallengeStatus = 2
	// Challenge was successfully validated.
	ChallengeStatus_CHALLENGE_STATUS_VALID ChallengeStatus = 3
	// Challenge validation failed.
	ChallengeStatus_CHALLENGE_STATUS_INVALID ChallengeStatus = 4
)

// Enum value maps for ChallengeStatus.
var (
	ChallengeStatus_name = map[int32]string{
		0: "CHALLENGE_STATUS_UNSPECIFIED",
		1: "CHALLENGE_STATUS_PENDING",
		2: "CHALLENGE_STATUS_PROCESSING",
		3: "CHALLENGE_STATUS_VALID",
		4: "CHALLENGE_STATUS_INVALID",
	}
	ChallengeStatus_value = map[string]int32{
		"CHALLENGE_STATUS_UNSPECIFIED": 0,
		"CHALLENGE_STATUS_PENDING":     1,
		"CHALLENGE_STATUS_PROCESSING":  2,
		"CHALLENGE_STATUS_VALID":       3,
		"CHALLENGE_STATUS_INVALID":     4,
	}
)

func (x ChallengeStatus) Enum() *ChallengeStatus {
	p := new(ChallengeStatus)
	*p = x
	return p
}

func (x ChallengeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChallengeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_acme_v1_challenge_proto_enumTypes[0].Descriptor()
}

func (ChallengeStatus) Type() protoreflect.EnumType {
	return &file_acme_v1_challenge_proto_enumTypes[0]
}

func (x ChallengeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChallengeStatus.Descriptor instead.
func (ChallengeStatus) EnumDescriptor() ([]byte, []int) {
	return file_acme_v1_challenge_proto_rawDescGZIP(), []int{0}
}

// ChallengeType specifies the validation method.
// RFC 8555 §9.7.8
type ChallengeType int32

const (
	// Unspecified challenge type.
	ChallengeType_CHALLENGE_TYPE_UNSPECIFIED ChallengeType = 0
	// HTTP challenge (§8.3).
	ChallengeType_CHALLENGE_TYPE_HTTP_01 ChallengeType = 1
	// DNS challenge (§8.4).
	ChallengeType_CHALLENGE_TYPE_DNS_01 ChallengeType = 2
	// TLS-ALPN challenge (RFC 8737).
	ChallengeType_CHALLENGE_TYPE_TLS_ALPN_01 ChallengeType = 3
)

// Enum value maps for ChallengeType.
var (
	ChallengeType_name = map[int32]string{
		0: "CHALLENGE_TYPE_UNSPECIFIED",
		1: "CHALLENGE_TYPE_HTTP_01",
		2: "CHALLENGE_TYPE_DNS_01",
		3: "CHALLENGE_TYPE_TLS_ALPN_01",
	}
	ChallengeType_value = map[string]int32{
		"CHALLENGE_TYPE_UNSPECIFIED": 0,
		"CHALLENGE_TYPE_HTTP_01":     1,
		"CHALLENGE_TYPE_DNS_01":      2,
		"CHALLENGE_TYPE_TLS_ALPN_01": 3,
	}
)

func (x ChallengeType) Enum() *ChallengeType {
	p := new(ChallengeType)
	*p = x
	return p
}

func (x ChallengeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChallengeType) Descriptor() protoreflect.EnumDescriptor {
	return file_acme_v1_challenge_proto_enumTypes[1].Descriptor()
}

func (ChallengeType) Type() protoreflect.EnumType {
	return &file_acme_v1_challenge_proto_enumTypes[1]
}

func (x ChallengeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChallengeType.Descriptor instead.
func (ChallengeType) EnumDescriptor() ([]byte, []int) {
	return file_acme_v1_challenge_proto_rawDescGZIP(), []int{1}
}

// Challenge represents a challenge for identifier validation.
// RFC 8555 §7.1.5, §8
type Challenge struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of challenge encoded in the object.
	Type ChallengeType `protobuf:"varint,1,opt,name=type,proto3,enum=acme.v1.ChallengeType" json:"type,omitempty"`
	// URL to which a response can be posted.
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	// Current status of the challenge.
	Status ChallengeStatus `protobuf:"varint,3,opt,name=status,proto3,enum=acme.v1.ChallengeStatus" json:"status,omitempty"`
	// Timestamp when the server validated the challenge.
	Validated string `protobuf:"bytes,4,opt,name=validated,proto3" json:"validated,omitempty"`
	// Error that occurred while the server was validating the challenge.
	Error *Problem `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	// Random value used to identify this challenge (§8).
	Token         string `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Challenge) Reset() {
	*x = Challenge{}
	mi := &file_acme_v1_challenge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Challenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Challenge) ProtoMessage() {}

func (x *Challenge) ProtoReflect() protoreflect.Message {
	mi := &file_acme_v1_challenge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Challenge.ProtoReflect.Descriptor instead.
func (*Challenge) Descriptor() ([]byte, []int) {
	return file_acme_v1_challenge_proto_rawDescGZIP(), []int{0}
}

func (x *Challenge) GetType() ChallengeType {
	if x != nil {
		return x.Type
	}
	return ChallengeType_CHALLENGE_TYPE_UNSPECIFIED
}

func (x *Challenge) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Challenge) GetStatus() ChallengeStatus {
	if x != nil {
		return x.Status
	}
	return ChallengeStatus_CHALLENGE_STATUS_UNSPECIFIED
}

func (x *Challenge) GetValidated() string {
	if x != nil {
		return x.Validated
	}
	return ""
}

func (x *Challenge) GetError() *Problem {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Challenge) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_acme_v1_challenge_proto protoreflect.FileDescriptor

const file_acme_v1_challenge_proto_rawDesc = "" +
	"\n" +
	"\x17acme/v1/challenge.proto\x12\aacme.v1\x1a\x15acme/v1/problem.proto\"\xd7\x01\n" +
	"\tChallenge\x12*\n" +
	"\x04type\x18\x01 \x01(\x0e2\x16.acme.v1.ChallengeTypeR\x04type\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x120\n" +
	"\x06status\x18\x03 \x01(\x0e2\x18.acme.v1.ChallengeStatusR\x06status\x12\x1c\n" +
	"\tvalidated\x18\x04 \x01(\tR\tvalidated\x12&\n" +
	"\x05error\x18\x05 \x01(\v2\x10.acme.v1.ProblemR\x05error\x12\x14\n" +
	"\x05token\x18\x06 \x01(\tR\x05token*\xac\x01\n" +
	"\x0fChallengeStatus\x12 \n" +
	"\x1cCHALLENGE_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18CHALLENGE_STATUS_PENDING\x10\x01\x12\x1f\n" +
	"\x1bCHALLENGE_STATUS_PROCESSING\x10\x02\x12\x1a\n" +
	"\x16CHALLENGE_STATUS_VALID\x10\x03\x12\x1c\n" +
	"\x18CHALLENGE_STATUS_INVALID\x10\x04*\x86\x01\n" +
	"\rChallengeType\x12\x1e\n" +
	"\x1aCHALLENGE_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16CHALLENGE_TYPE_HTTP_01\x10\x01\x12\x19\n" +
	"\x15CHALLENGE_TYPE_DNS_01\x10\x02\x12\x1e\n" +
	"\x1aCHALLENGE_TYPE_TLS_ALPN_01\x10\x03B%Z#darvaza.org/wilee/pkg/specs/acme/v1b\x06proto3"

var (
	file_acme_v1_challenge_proto_rawDescOnce sync.Once
	file_acme_v1_challenge_proto_rawDescData []byte
)

func file_acme_v1_challenge_proto_rawDescGZIP() []byte {
	file_acme_v1_challenge_proto_rawDescOnce.Do(func() {
		file_acme_v1_challenge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_acme_v1_challenge_proto_rawDesc), len(file_acme_v1_challenge_proto_rawDesc)))
	})
	return file_acme_v1_challenge_proto_rawDescData
}

var file_acme_v1_challenge_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_acme_v1_challenge_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_acme_v1_challenge_proto_goTypes = []any{
	(ChallengeStatus)(0), // 0: acme.v1.ChallengeStatus
	(ChallengeType)(0),   // 1: acme.v1.ChallengeType
	(*Challenge)(nil),    // 2: acme.v1.Challenge
	(*Problem)(nil),      // 3: acme.v1.Problem
}
var file_acme_v1_challenge_proto_depIdxs = []int32{
	1, // 0: acme.v1.Challenge.type:type_name -> acme.v1.ChallengeType
	0, // 1: acme.v1.Challenge.status:type_name -> acme.v1.ChallengeStatus
	3, // 2: acme.v1.Challenge.error:type_name -> acme.v1.Problem
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_acme_v1_challenge_proto_init() }
func file_acme_v1_challenge_proto_init() {
	if File_acme_v1_challenge_proto != nil {
		return
	}
	file_acme_v1_problem_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_acme_v1_challenge_proto_rawDesc), len(file_acme_v1_challenge_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_acme_v1_challenge_proto_goTypes,
		DependencyIndexes: file_acme_v1_challenge_proto_depIdxs,
		EnumInfos:         file_acme_v1_challenge_proto_enumTypes,
		MessageInfos:      file_acme_v1_challenge_proto_msgTypes,
	}.Build()
	File_acme_v1_challenge_proto = out.File
	file_acme_v1_challenge_proto_goTypes = nil
	file_acme_v1_challenge_proto_depIdxs = nil
}
