// Copyright (c) 2024-2026 Apptly Software Ltd <oss@apptly.co>
// SPDX-License-Identifier: MIT
//
// ACME Order Resource (RFC 8555)

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: acme/v1/order.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OrderStatus represents the status of an ACME order.
// RFC 8555 §7.1.6
type OrderStatus int32

const (
	// Unspecified order status.
	OrderStatus_ORDER_STATUS_UNSPECIFIED OrderStatus = 0
	// Order is awaiting authorisation completion.
	OrderStatus_ORDER_STATUS_PENDING OrderStatus = 1
	// All authorisations are complete; order can be finalised.
	OrderStatus_ORDER_STATUS_READY OrderStatus = 2
	// Certificate is being issued.
	OrderStatus_ORDER_STATUS_PROCESSING OrderStatus = 3
	// Certificate has been issued.
	OrderStatus_ORDER_STATUS_VALID OrderStatus = 4
	// Order failed; see error field for details.
	OrderStatus_ORDER_STATUS_INVALID OrderStatus = 5
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNSPECIFIED",
		1: "ORDER_STATUS_PENDING",
		2: "ORDER_STATUS_READY",
		3: "ORDER_STATUS_PROCESSING",
		4: "ORDER_STATUS_VALID",
		5: "ORDER_STATUS_INVALID",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED": 0,
		"ORDER_STATUS_PENDING":     1,
		"ORDER_STATUS_READY":       2,
		"ORDER_STATUS_PROCESSING":  3,
		"ORDER_STATUS_VALID":       4,
		"ORDER_STATUS_INVALID":     5,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_acme_v1_order_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_acme_v1_order_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_acme_v1_order_proto_rawDescGZIP(), []int{0}
}

// Order represents a certificate order.
// RFC 8555 §7.1.3
type Order struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current status of the order.
	Status OrderStatus `protobuf:"varint,1,opt,name=status,proto3,enum=acme.v1.OrderStatus" json:"status,omitempty"`
	// Timestamp after which the server will consider this order invalid.
	Expires string `protobuf:"bytes,2,opt,name=expires,proto3" json:"expires,omitempty"`
	// Array of identifier objects that the order pertains to.
	Identifiers []*Identifier `protobuf:"bytes,3,rep,name=identifiers,proto3" json:"identifiers,omitempty"`
	// Requested value of the notBefore field in the certificate.
	NotBefore string `protobuf:"bytes,4,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	// Requested value of the notAfter field in the certificate.
	NotAfter string `protobuf:"bytes,5,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	// Error that occurred while processing the order, if any.
	Error *Problem `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	// URLs for authorisation objects the client must satisfy.
	Authorizations []string `protobuf:"bytes,7,rep,name=authorizations,proto3" json:"authorizations,omitempty"`
	// URL that a CSR must be POSTed to once all authorisations are satisfied.
	Finalize string `protobuf:"bytes,8,opt,name=finalize,proto3" json:"finalize,omitempty"`
	// URL for the certificate that has been issued in response to this order.
	Certificate   string `protobuf:"bytes,9,opt,name=certificate,proto3" json:"certificate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_acme_v1_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_acme_v1_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_acme_v1_order_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *Order) GetExpires() string {
	if x != nil {
		return x.Expires
	}
	return ""
}

func (x *Order) GetIdentifiers() []*Identifier {
	if x != nil {
		return x.Identifiers
	}
	return nil
}

func (x *Order) GetNotBefore() string {
	if x != nil {
		return x.NotBefore
	}
	return ""
}

func (x *Order) GetNotAfter() string {
	if x != nil {
		return x.NotAfter
	}
	return ""
}

func (x *Order) GetError() *Problem {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Order) GetAuthorizations() []string {
	if x != nil {
		return x.Authorizations
	}
	return nil
}

func (x *Order) GetFinalize() string {
	if x != nil {
		return x.Finalize
	}
	return ""
}

func (x *Order) GetCertificate() string {
	if x != nil {
		return x.Certificate
	}
	return ""
}

var File_acme_v1_order_proto protoreflect.FileDescriptor

const file_acme_v1_order_proto_rawDesc = "" +
	"\n" +
	"\x13acme/v1/order.proto\x12\aacme.v1\x1a\x12acme/v1/acme.proto\x1a\x15acme/v1/problem.proto\"\xd0\x02\n" +
	"\x05Order\x12,\n" +
	"\x06status\x18\x01 \x01(\x0e2\x14.acme.v1.OrderStatusR\x06status\x12\x18\n" +
	"\aexpires\x18\x02 \x01(\tR\aexpires\x125\n" +
	"\videntifiers\x18\x03 \x03(\v2\x13.acme.v1.IdentifierR\videntifiers\x12\x1d\n" +
	"\n" +
	"not_before\x18\x04 \x01(\tR\tnotBefore\x12\x1b\n" +
	"\tnot_after\x18\x05 \x01(\tR\bnotAfter\x12&\n" +
	"\x05error\x18\x06 \x01(\v2\x10.acme.v1.ProblemR\x05error\x12&\n" +
	"\x0eauthorizations\x18\a \x03(\tR\x0eauthorizations\x12\x1a\n" +
	"\bfinalize\x18\b \x01(\tR\bfinalize\x12 \n" +
	"\vcertificate\x18\t \x01(\tR\vcertificate*\xac\x01\n" +
	"\vOrderStatus\x12\x1c\n" +
	"\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ORDER_STATUS_PENDING\x10\x01\x12\x16\n" +
	"\x12ORDER_STATUS_READY\x10\x02\x12\x1b\n" +
	"\x17ORDER_STATUS_PROCESSING\x10\x03\x12\x16\n" +
	"\x12ORDER_STATUS_VALID\x10\x04\x12\x18\n" +
	"\x14ORDER_STATUS_INVALID\x10\x05B%Z#darvaza.org/wilee/pkg/specs/acme/v1b\x06proto3"

var (
	file_acme_v1_order_proto_rawDescOnce sync.Once
	file_acme_v1_order_proto_rawDescData []byte
)

func file_acme_v1_order_proto_rawDescGZIP() []byte {
	file_acme_v1_order_proto_rawDescOnce.Do(func() {
		file_acme_v1_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_acme_v1_order_proto_rawDesc), len(file_acme_v1_order_proto_rawDesc)))
	})
	return file_acme_v1_order_proto_rawDescData
}

var file_acme_v1_order_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_acme_v1_order_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_acme_v1_order_proto_goTypes = []any{
	(OrderStatus)(0),   // 0: acme.v1.OrderStatus
	(*Order)(nil),      // 1: acme.v1.Order
	(*Identifier)(nil), // 2: acme.v1.Identifier
	(*Problem)(nil),    // 3: acme.v1.Problem
}
var file_acme_v1_order_proto_depIdxs = []int32{
	0, // 0: acme.v1.Order.status:type_name -> acme.v1.OrderStatus
	2, // 1: acme.v1.Order.identifiers:type_name -> acme.v1.Identifier
	3, // 2: acme.v1.Order.error:type_name -> acme.v1.Problem
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_acme_v1_order_proto_init() }
func file_acme_v1_order_proto_init() {
	if File_acme_v1_order_proto != nil {
		return
	}
	file_acme_v1_acme_proto_init()
	file_acme_v1_problem_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_acme_v1_order_proto_rawDesc), len(file_acme_v1_order_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_acme_v1_order_proto_goTypes,
		DependencyIndexes: file_acme_v1_order_proto_depIdxs,
		EnumInfos:         file_acme_v1_order_proto_enumTypes,
		MessageInfos:      file_acme_v1_order_proto_msgTypes,
	}.Build()
	File_acme_v1_order_proto = out.File
	file_acme_v1_order_proto_goTypes = nil
	file_acme_v1_order_proto_depIdxs = nil
}
