// Copyright (c) 2024-2026 Apptly Software Ltd <oss@apptly.co>
// SPDX-License-Identifier: MIT
//
// ACME Problem Details (RFC 7807, RFC 8555)

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: acme/v1/problem.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorType specifies the ACME error type.
// RFC 8555 §9.7.4
type ErrorType int32

const (
	// Unspecified error type.
	ErrorType_ERROR_TYPE_UNSPECIFIED ErrorType = 0
	// The request specified an account that does not exist.
	ErrorType_ERROR_TYPE_ACCOUNT_DOES_NOT_EXIST ErrorType = 1
	// The request specified a certificate to be revoked that has already been revoked.
	ErrorType_ERROR_TYPE_ALREADY_REVOKED ErrorType = 2
	// The CSR is unacceptable.
	ErrorType_ERROR_TYPE_BAD_CSR ErrorType = 3
	// The client sent an unacceptable anti-replay nonce.
	ErrorType_ERROR_TYPE_BAD_NONCE ErrorType = 4
	// The JWS was signed with a public key the server does not support.
	ErrorType_ERROR_TYPE_BAD_PUBLIC_KEY ErrorType = 5
	// The revocation reason provided is not allowed by the server.
	ErrorType_ERROR_TYPE_BAD_REVOCATION_REASON ErrorType = 6
	// The JWS was signed with an algorithm the server does not support.
	ErrorType_ERROR_TYPE_BAD_SIGNATURE_ALGORITHM ErrorType = 7
	// CAA records forbid the CA from issuing a certificate.
	ErrorType_ERROR_TYPE_CAA ErrorType = 8
	// Specific error conditions are indicated in subproblems.
	ErrorType_ERROR_TYPE_COMPOUND ErrorType = 9
	// The server could not connect to validation target.
	ErrorType_ERROR_TYPE_CONNECTION ErrorType = 10
	// There was a problem with a DNS query during identifier validation.
	ErrorType_ERROR_TYPE_DNS ErrorType = 11
	// The request must include a value for the externalAccountBinding field.
	ErrorType_ERROR_TYPE_EXTERNAL_ACCOUNT_REQUIRED ErrorType = 12
	// Response received did not match the challenge's requirements.
	ErrorType_ERROR_TYPE_INCORRECT_RESPONSE ErrorType = 13
	// A contact URL for an account was invalid.
	ErrorType_ERROR_TYPE_INVALID_CONTACT ErrorType = 14
	// The request message was malformed.
	ErrorType_ERROR_TYPE_MALFORMED ErrorType = 15
	// The request attempted to finalise an order that is not ready.
	ErrorType_ERROR_TYPE_ORDER_NOT_READY ErrorType = 16
	// The request exceeds a rate limit.
	ErrorType_ERROR_TYPE_RATE_LIMITED ErrorType = 17
	// The server will not issue certificates for the identifier.
	ErrorType_ERROR_TYPE_REJECTED_IDENTIFIER ErrorType = 18
	// The server experienced an internal error.
	ErrorType_ERROR_TYPE_SERVER_INTERNAL ErrorType = 19
	// The server received a TLS error during validation.
	ErrorType_ERROR_TYPE_TLS ErrorType = 20
	// The client lacks sufficient authorisation.
	ErrorType_ERROR_TYPE_UNAUTHORIZED ErrorType = 21
	// A contact URL used an unsupported protocol scheme.
	ErrorType_ERROR_TYPE_UNSUPPORTED_CONTACT ErrorType = 22
	// An identifier is of an unsupported type.
	ErrorType_ERROR_TYPE_UNSUPPORTED_IDENTIFIER ErrorType = 23
	// Visit the "instance" URL and take actions specified there.
	ErrorType_ERROR_TYPE_USER_ACTION_REQUIRED ErrorType = 24
)

// Enum value maps for ErrorType.
var (
	ErrorType_name = map[int32]string{
		0:  "ERROR_TYPE_UNSPECIFIED",
		1:  "ERROR_TYPE_ACCOUNT_DOES_NOT_EXIST",
		2:  "ERROR_TYPE_ALREADY_REVOKED",
		3:  "ERROR_TYPE_BAD_CSR",
		4:  "ERROR_TYPE_BAD_NONCE",
		5:  "ERROR_TYPE_BAD_PUBLIC_KEY",
		6:  "ERROR_TYPE_BAD_REVOCATION_REASON",
		7:  "ERROR_TYPE_BAD_SIGNATURE_ALGORITHM",
		8:  "ERROR_TYPE_CAA",
		9:  "ERROR_TYPE_COMPOUND",
		10: "ERROR_TYPE_CONNECTION",
		11: "ERROR_TYPE_DNS",
		12: "ERROR_TYPE_EXTERNAL_ACCOUNT_REQUIRED",
		13: "ERROR_TYPE_INCORRECT_RESPONSE",
		14: "ERROR_TYPE_INVALID_CONTACT",
		15: "ERROR_TYPE_MALFORMED",
		16: "ERROR_TYPE_ORDER_NOT_READY",
		17: "ERROR_TYPE_RATE_LIMITED",
		18: "ERROR_TYPE_REJECTED_IDENTIFIER",
		19: "ERROR_TYPE_SERVER_INTERNAL",
		20: "ERROR_TYPE_TLS",
		21: "ERROR_TYPE_UNAUTHORIZED",
		22: "ERROR_TYPE_UNSUPPORTED_CONTACT",
		23: "ERROR_TYPE_UNSUPPORTED_IDENTIFIER",
		24: "ERROR_TYPE_USER_ACTION_REQUIRED",
	}
	ErrorType_value = map[string]int32{
		"ERROR_TYPE_UNSPECIFIED":               0,
		"ERROR_TYPE_ACCOUNT_DOES_NOT_EXIST":    1,
		"ERROR_TYPE_ALREADY_REVOKED":           2,
		"ERROR_TYPE_BAD_CSR":                   3,
		"ERROR_TYPE_BAD_NONCE":                 4,
		"ERROR_TYPE_BAD_PUBLIC_KEY":            5,
		"ERROR_TYPE_BAD_REVOCATION_REASON":     6,
		"ERROR_TYPE_BAD_SIGNATURE_ALGORITHM":   7,
		"ERROR_TYPE_CAA":                       8,
		"ERROR_TYPE_COMPOUND":                  9,
		"ERROR_TYPE_CONNECTION":                10,
		"ERROR_TYPE_DNS":                       11,
		"ERROR_TYPE_EXTERNAL_ACCOUNT_REQUIRED": 12,
		"ERROR_TYPE_INCORRECT_RESPONSE":        13,
		"ERROR_TYPE_INVALID_CONTACT":           14,
		"ERROR_TYPE_MALFORMED":                 15,
		"ERROR_TYPE_ORDER_NOT_READY":           16,
		"ERROR_TYPE_RATE_LIMITED":              17,
		"ERROR_TYPE_REJECTED_IDENTIFIER":       18,
		"ERROR_TYPE_SERVER_INTERNAL":           19,
		"ERROR_TYPE_TLS":                       20,
		"ERROR_TYPE_UNAUTHORIZED":              21,
		"ERROR_TYPE_UNSUPPORTED_CONTACT":       22,
		"ERROR_TYPE_UNSUPPORTED_IDENTIFIER":    23,
		"ERROR_TYPE_USER_ACTION_REQUIRED":      24,
	}
)

func (x ErrorType) Enum() *ErrorType {
	p := new(ErrorType)
	*p = x
	return p
}

func (x ErrorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorType) Descriptor() protoreflect.EnumDescriptor {
	return file_acme_v1_problem_proto_enumTypes[0].Descriptor()
}

func (ErrorType) Type() protoreflect.EnumType {
	return &file_acme_v1_problem_proto_enumTypes[0]
}

func (x ErrorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorType.Descriptor instead.
func (ErrorType) EnumDescriptor() ([]byte, []int) {
	return file_acme_v1_problem_proto_rawDescGZIP(), []int{0}
}

// Problem represents an error response.
// RFC 7807 §3, RFC 8555 §6.7
type Problem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// URI reference that identifies the problem type.
	Type ErrorType `protobuf:"varint,1,opt,name=type,proto3,enum=acme.v1.ErrorType" json:"type,omitempty"`
	// Short, human-readable summary of the problem type.
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// HTTP status code generated by the origin server.
	Status int32 `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	// Human-readable explanation specific to this occurrence.
	Detail string `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	// URI reference that identifies the specific occurrence.
	Instance string `protobuf:"bytes,5,opt,name=instance,proto3" json:"instance,omitempty"`
	// Array of problems applying to specific identifiers (§6.7.1).
	Subproblems   []*Subproblem `protobuf:"bytes,6,rep,name=subproblems,proto3" json:"subproblems,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Problem) Reset() {
	*x = Problem{}
	mi := &file_acme_v1_problem_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Problem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Problem) ProtoMessage() {}

func (x *Problem) ProtoReflect() protoreflect.Message {
	mi := &file_acme_v1_problem_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Problem.ProtoReflect.Descriptor instead.
func (*Problem) Descriptor() ([]byte, []int) {
	return file_acme_v1_problem_proto_rawDescGZIP(), []int{0}
}

func (x *Problem) GetType() ErrorType {
	if x != nil {
		return x.Type
	}
	return ErrorType_ERROR_TYPE_UNSPECIFIED
}

func (x *Problem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Problem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Problem) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *Problem) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *Problem) GetSubproblems() []*Subproblem {
	if x != nil {
		return x.Subproblems
	}
	return nil
}

// Subproblem represents a component error within a Problem.
// RFC 8555 §6.7.1
type Subproblem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// URI reference that identifies the problem type.
	Type ErrorType `protobuf:"varint,1,opt,name=type,proto3,enum=acme.v1.ErrorType" json:"type,omitempty"`
	// Human-readable explanation specific to this subproblem.
	Detail string `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	// The identifier to which this subproblem refers.
	Identifier    *Identifier `protobuf:"bytes,3,opt,name=identifier,proto3" json:"identifier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subproblem) Reset() {
	*x = Subproblem{}
	mi := &file_acme_v1_problem_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subproblem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subproblem) ProtoMessage() {}

func (x *Subproblem) ProtoReflect() protoreflect.Message {
	mi := &file_acme_v1_problem_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subproblem.ProtoReflect.Descriptor instead.
func (*Subproblem) Descriptor() ([]byte, []int) {
	return file_acme_v1_problem_proto_rawDescGZIP(), []int{1}
}

func (x *Subproblem) GetType() ErrorType {
	if x != nil {
		return x.Type
	}
	return ErrorType_ERROR_TYPE_UNSPECIFIED
}

func (x *Subproblem) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *Subproblem) GetIdentifier() *Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

var File_acme_v1_problem_proto protoreflect.FileDescriptor

const file_acme_v1_problem_proto_rawDesc = "" +
	"\n" +
	"\x15acme/v1/problem.proto\x12\aacme.v1\x1a\x12acme/v1/acme.proto\"\xca\x01\n" +
	"\aProblem\x12&\n" +
	"\x04type\x18\x01 \x01(\x0e2\x12.acme.v1.ErrorTypeR\x04type\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\x12\x1a\n" +
	"\binstance\x18\x05 \x01(\tR\binstance\x125\n" +
	"\vsubproblems\x18\x06 \x03(\v2\x13.acme.v1.SubproblemR\vsubproblems\"\x81\x01\n" +
	"\n" +
	"Subproblem\x12&\n" +
	"\x04type\x18\x01 \x01(\x0e2\x12.acme.v1.ErrorTypeR\x04type\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\x123\n" +
	"\n" +
	"identifier\x18\x03 \x01(\v2\x13.acme.v1.IdentifierR\n" +
	"identifier*\x92\x06\n" +
	"\tErrorType\x12\x1a\n" +
	"\x16ERROR_TYPE_UNSPECIFIED\x10\x00\x12%\n" +
	"!ERROR_TYPE_ACCOUNT_DOES_NOT_EXIST\x10\x01\x12\x1e\n" +
	"\x1aERROR_TYPE_ALREADY_REVOKED\x10\x02\x12\x16\n" +
	"\x12ERROR_TYPE_BAD_CSR\x10\x03\x12\x18\n" +
	"\x14ERROR_TYPE_BAD_NONCE\x10\x04\x12\x1d\n" +
	"\x19ERROR_TYPE_BAD_PUBLIC_KEY\x10\x05\x12$\n" +
	" ERROR_TYPE_BAD_REVOCATION_REASON\x10\x06\x12&\n" +
	"\"ERROR_TYPE_BAD_SIGNATURE_ALGORITHM\x10\a\x12\x12\n" +
	"\x0eERROR_TYPE_CAA\x10\b\x12\x17\n" +
	"\x13ERROR_TYPE_COMPOUND\x10\t\x12\x19\n" +
	"\x15ERROR_TYPE_CONNECTION\x10\n" +
	"\x12\x12\n" +
	"\x0eERROR_TYPE_DNS\x10\v\x12(\n" +
	"$ERROR_TYPE_EXTERNAL_ACCOUNT_REQUIRED\x10\f\x12!\n" +
	"\x1dERROR_TYPE_INCORRECT_RESPONSE\x10\r\x12\x1e\n" +
	"\x1aERROR_TYPE_INVALID_CONTACT\x10\x0e\x12\x18\n" +
	"\x14ERROR_TYPE_MALFORMED\x10\x0f\x12\x1e\n" +
	"\x1aERROR_TYPE_ORDER_NOT_READY\x10\x10\x12\x1b\n" +
	"\x17ERROR_TYPE_RATE_LIMITED\x10\x11\x12\"\n" +
	"\x1eERROR_TYPE_REJECTED_IDENTIFIER\x10\x12\x12\x1e\n" +
	"\x1aERROR_TYPE_SERVER_INTERNAL\x10\x13\x12\x12\n" +
	"\x0eERROR_TYPE_TLS\x10\x14\x12\x1b\n" +
	"\x17ERROR_TYPE_UNAUTHORIZED\x10\x15\x12\"\n" +
	"\x1eERROR_TYPE_UNSUPPORTED_CONTACT\x10\x16\x12%\n" +
	"!ERROR_TYPE_UNSUPPORTED_IDENTIFIER\x10\x17\x12#\n" +
	"\x1fERROR_TYPE_USER_ACTION_REQUIRED\x10\x18B%Z#darvaza.org/wilee/pkg/specs/acme/v1b\x06proto3"

var (
	file_acme_v1_problem_proto_rawDescOnce sync.Once
	file_acme_v1_problem_proto_rawDescData []byte
)

func file_acme_v1_problem_proto_rawDescGZIP() []byte {
	file_acme_v1_problem_proto_rawDescOnce.Do(func() {
		file_acme_v1_problem_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_acme_v1_problem_proto_rawDesc), len(file_acme_v1_problem_proto_rawDesc)))
	})
	return file_acme_v1_problem_proto_rawDescData
}

var file_acme_v1_problem_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_acme_v1_problem_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_acme_v1_problem_proto_goTypes = []any{
	(ErrorType)(0),     // 0: acme.v1.ErrorType
	(*Problem)(nil),    // 1: acme.v1.Problem
	(*Subproblem)(nil), // 2: acme.v1.Subproblem
	(*Identifier)(nil), // 3: acme.v1.Identifier
}
var file_acme_v1_problem_proto_depIdxs = []int32{
	0, // 0: acme.v1.Problem.type:type_name -> acme.v1.ErrorType
	2, // 1: acme.v1.Problem.subproblems:type_name -> acme.v1.Subproblem
	0, // 2: acme.v1.Subproblem.type:type_name -> acme.v1.ErrorType
	3, // 3: acme.v1.Subproblem.identifier:type_name -> acme.v1.Identifier
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_acme_v1_problem_proto_init() }
func file_acme_v1_problem_proto_init() {
	if File_acme_v1_problem_proto != nil {
		return
	}
	file_acme_v1_acme_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_acme_v1_problem_proto_rawDesc), len(file_acme_v1_problem_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_acme_v1_problem_proto_goTypes,
		DependencyIndexes: file_acme_v1_problem_proto_depIdxs,
		EnumInfos:         file_acme_v1_problem_proto_enumTypes,
		MessageInfos:      file_acme_v1_problem_proto_msgTypes,
	}.Build()
	File_acme_v1_problem_proto = out.File
	file_acme_v1_problem_proto_goTypes = nil
	file_acme_v1_problem_proto_depIdxs = nil
}
